### ISSUE TITLE
Timeouts and IO Errors

### ISSUE THREAD

**Issue by akamalov** [GalacticFog/gestalt-dcos#3]
Deployed via DCOS v1.7. Creating an organization or workarea or anything else proved to be challenging. Already created organization disappears  and then start re-appears constantly. Getting `An I/O error occurred while sending to the backend.`

**Comment by cgbaker** [comment]
This is a bug with VIPs in DC/OS. I'm actually writing some documentation around this write now. This issue is supposedly addressed in version 1.7.1 of DCOS (not available as open-source yet): 
https://groups.google.com/a/dcos.io/forum/?utm_medium=email&utm_source=footer#!msg/users/bKv9mucQBi0/H5VUg17nAAAJ

Reconfiguring all agents nodes with the following systctl commands addresses the issue: 
https://github.com/dcos/dcos/blob/master/packages/minuteman/build#L28-L30

**Comment by akamalov** [comment]
@cgbaker  thanks so much for prompt reply.  Implemented the option with `sysctl`, however, getting yet another error:

`You do not have permission to perform this action. Failed: 'workspace.create'`

Currently logged on with `gestalt-admin` account.

**Comment by cgbaker** [comment]
So, you created an org and then attempted to create a workspace and got the error? Was the org created before the `sysctl` solution? It's likely that the org was created but the default entitlements couldn't be set because of communication issues to the database. Try deleting the org or working from a new one.

**Comment by akamalov** [comment]
Thanks @cgbaker. Will re-create it!!

**Comment by cgbaker** [comment]
if that doesn't address the issue, please open a new issue. thanks!

**Comment by akamalov** [comment]
Issue addressed, @cgbaker  thanks so much!!
